### ISSUE TITLE
change favicon from react app default image

### ISSUE THREAD

**Issue by go-bears** [kiva/crowdvet.org#29]
currently the favicon the default react app icon. it would be nice to switch it out for something more applicable to crowdvet.

**Comment by avdeepd** [comment]
I can try and take this on!

**Comment by abdiG** [comment]
Hi @go-bears, i would like to work on this issue. I have already forked it  and downloaded into my local machine. But i am required to 'Set dev.js file inside config folder'. i don't have config folder nor keys required to run this project. Please help me set up the project.

**Comment by go-bears** [comment]
Hi @abdiG thanks for your interest in working on the project! This issue is currently worked on by @avdeepd 

Those credentials aren't needed for working on the beginner's issues. I downloaded the development branch and was able to run the site locally using ```npm run dev```

**Comment by leslie-alldridge** [comment]
Hi @go-bears I noticed this is still pending 11 days later so I decided to jump in. Also I noticed on develop my linting was picking up many images without alt tags (I think these are important personally for users with accessibility issues). Would you like me to add those on a separate issue? Cheers

**Comment by go-bears** [comment]
@avdeepd  please review https://github.com/kiva/crowdvet.org/pull/30
did you want to use the Kiva "K" or did your team want a different logo or letter?

**Comment by go-bears** [comment]
@leslie-alldridge thanks for your interest in contributing to Kiva's open source repos! 
We'll need to hear from either @avdeepd  or @alyssalaten to approve the PR. 

But many thanks for bringing the accessibility issue to our attention! I'll file an issue for it and feel free to have a go at it.

**Comment by leslie-alldridge** [comment]
Awesome thanks @go-bears , I can change the favicon to anything else if required. I've just commented on the alt tag issue and will get that sorted tonight. I noticed my 'prettier' linting adjusted the file slightly (spacing wise) so I'll be sure to disable that in future.
