### ISSUE TITLE
Add alt tags to images for accessiblity 

### ISSUE THREAD

**Issue by go-bears** [kiva/crowdvet.org#31]
There are images without alt tags which limit access to users who are are reliant on screen readers for engaging with the crowdvet website.

**Comment by leslie-alldridge** [comment]
I'll look into this tonight and submit a PR, cheers

**Comment by go-bears** [comment]
thanks for bringing this to our attention @leslie-alldridge !

**Comment by leslie-alldridge** [comment]
@go-bears I've completed a few components so far but the ones hidden behind Auth I'm having trouble viewing in my dev environment. Do I need to set up a test database and have the back end server running? I've created a dev.js config file but not sure what variables to use. If you have any other advice that'd be much appreciated, cheers!

**Comment by go-bears** [comment]
Hi @leslie-alldridge appreciate the work you're putting into making crowdvet better!

Yes, crowdvet has a backend server running. I imagine the images behind the auth are to draw up the new enterprises that are being vetted at the moment. Given that those enterprises would change, changing the associated image as well,  it'd be ok to leave those image tags alone for now.  Does this approach jive with you @alyssalaten ?

**Comment by alyssalaten** [comment]
@go-bears having a little trouble following.. the photos on crowdvet.org/vet/enterprises are ones we've manually chosen and uploaded. we upload these to AWS, then to the admin site for crowdvet. of course, always new enterprises + photos going up

**Comment by leslie-alldridge** [comment]
I could do something generic such as alt='image showing enterprise'

**Comment by go-bears** [comment]
thanks for confirming that the images are dynamic @alyssalaten ! @leslie-alldridge I'm ok with the approach you're proposing.

**Comment by leslie-alldridge** [comment]
PR ready @alyssalaten @go-bears  cheers
